### PR TITLE
Gtag

### PR DESCRIPTION
**Pull request by metasoares**
Review the code and let me know for changes if it is still required.

### CODE REVIEW

**Comment by xiaojian-hong** [comment]
Hi @metasoares ,
Do you want to add the Google Analytics tracking code to https://presence.js.org/?
The website of this domain is on the [gh-pages](https://github.com/yomorun/presence.js.org/tree/gh-pages) branch, which was generated by GitHub Pages.
So I think you should add the GA tracking code into the `gh-pages` branch?
You could also check this link for reference. https://desiredpersona.com/google-analytics-jekyll/

**Review by fanweixiao — CHANGES_REQUESTED** [review]
wrong. The Goal is as what @xiaojian-hong commented. Please fix it and update the system.

**Comment by metasoares** [comment]
Error-faced: I have tried to make changes on gh-pages repo and faced errors and realized it requires jekyll

To add gtag to a github website pages it requires to make changes locally with [jekyll](https://jekyllrb.com/docs/themes/). I am installing[ bundler](https://bundler.io/).

**Comment by xiaojian-hong** [comment]
We are using the theme [Cayman](https://github.com/pages-themes/cayman#configuration-variables), it automatically added the GA tracking code after we added the `google_analytics` to `_config.yml` file.

**Pull request closed without merging**
